services:
  # web-api:
  #   image: ${DOCKER_REGISTRY-}webapi
  #   container_name: web-api
  #   build:
  #     context: .
  #     dockerfile: src/Web.Api/Dockerfile
  #   ports:
  #     - 5000:8080
  #     - 5001:8081

  app:
    container_name: expense-tracker-developer
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-999}
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode-server:/home/developer/.vscode-server
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway

    ports:
      - "5000:5000"
      - "5100:5100"
      - "5200:5200"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8082:80

volumes:
  postgres-data:
  vscode-server:
