services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.dev
      args:
        - USER_UID=${UID:-1000}
        - USER_GID=${GID:-1000}
        - DOCKER_GROUP_ID=${DOCKER_GROUP_ID:-999}
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
      - vscode-server:/home/developer/.vscode-server
    tty: true
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - "5000:5000"
      - "5100:5100"
      - "5200:5200"

volumes:
  vscode-server:
