// <auto-generated />
using Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable enable

namespace Infrastructure.Database.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        _ = modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        _ = modelBuilder.Entity("Domain.Categories.Category", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            _ = b.HasKey("Id")
                .HasName("pk_categories");

            _ = b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_categories_name");

            _ = b.ToTable("categories", "public");
        });

        _ = modelBuilder.Entity("Domain.Expenses.Expense", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<decimal>("Amount")
                .HasPrecision(18, 2)
                .HasColumnType("numeric(18,2)");

            _ = b.Property<Guid>("CategoryId")
                .HasColumnType("uuid");

            _ = b.Property<DateTime>("CreatedAt")
                .HasColumnType("timestamp with time zone");

            _ = b.Property<DateOnly>("Date")
                .HasColumnType("date");

            _ = b.Property<string>("Description")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)");

            _ = b.Property<Guid>("PaymentMethodId")
                .HasColumnType("uuid");

            _ = b.Property<DateTime?>("UpdatedAt")
                .HasColumnType("timestamp with time zone");

            _ = b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            _ = b.HasKey("Id")
                .HasName("pk_expenses");

            _ = b.HasIndex("CategoryId")
                .HasDatabaseName("ix_expenses_category_id");

            _ = b.HasIndex("PaymentMethodId")
                .HasDatabaseName("ix_expenses_payment_method_id");

            _ = b.HasIndex("UserId")
                .HasDatabaseName("ix_expenses_user_id");

            _ = b.ToTable("expenses", "public");
        });

        _ = modelBuilder.Entity("Domain.Expenses.ExpenseTag", b =>
        {
            _ = b.Property<Guid>("ExpenseId")
                .HasColumnType("uuid");

            _ = b.Property<Guid>("TagId")
                .HasColumnType("uuid");

            _ = b.HasKey("ExpenseId", "TagId")
                .HasName("pk_expense_tag");

            _ = b.HasIndex("TagId")
                .HasDatabaseName("ix_expense_tag_tag_id");

            _ = b.ToTable("expense_tag", "public");
        });

        _ = modelBuilder.Entity("Domain.PaymentMethods.PaymentMethod", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            _ = b.HasKey("Id")
                .HasName("pk_payment_methods");

            _ = b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_payment_methods_name");

            _ = b.ToTable("payment_methods", "public");
        });

        _ = modelBuilder.Entity("Domain.Roles.Role", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            _ = b.HasKey("Id")
                .HasName("pk_roles");

            _ = b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_roles_name");

            _ = b.ToTable("roles", "public");
        });

        _ = modelBuilder.Entity("Domain.Roles.RolePermission", b =>
        {
            _ = b.Property<string>("Permission")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)");

            _ = b.Property<Guid>("RoleId")
                .HasColumnType("uuid");

            _ = b.HasKey("RoleId", "Permission")
                .HasName("pk_role_permissions");

            _ = b.ToTable("role_permissions", "public");
        });

        _ = modelBuilder.Entity("Domain.Roles.UserRole", b =>
        {
            _ = b.Property<Guid>("RoleId")
                .HasColumnType("uuid");

            _ = b.Property<Guid>("UserId")
                .HasColumnType("uuid");

            _ = b.HasKey("UserId", "RoleId")
                .HasName("pk_user_roles");

            _ = b.HasIndex("RoleId")
                .HasDatabaseName("ix_user_roles_role_id");

            _ = b.ToTable("user_roles", "public");
        });

        _ = modelBuilder.Entity("Domain.Tags.Tag", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<string>("Name")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)");

            _ = b.HasKey("Id")
                .HasName("pk_tags");

            _ = b.HasIndex("Name")
                .IsUnique()
                .HasDatabaseName("ix_tags_name");

            _ = b.ToTable("tags", "public");
        });

        _ = modelBuilder.Entity("Domain.Users.User", b =>
        {
            _ = b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid");

            _ = b.Property<string>("Email")
                .IsRequired()
                .HasColumnType("text");

            _ = b.Property<string>("FirstName")
                .IsRequired()
                .HasColumnType("text");

            _ = b.Property<string>("LastName")
                .IsRequired()
                .HasColumnType("text");

            _ = b.Property<string>("PasswordHash")
                .IsRequired()
                .HasColumnType("text");

            _ = b.Property<int>("PermissionVersion")
                .HasColumnType("integer");

            _ = b.HasKey("Id")
                .HasName("pk_users");

            _ = b.HasIndex("Email")
                .IsUnique()
                .HasDatabaseName("ix_users_email");

            _ = b.ToTable("users", "public");
        });

        _ = modelBuilder.Entity("Domain.Expenses.Expense", b =>
        {
            _ = b.HasOne("Domain.Categories.Category", null)
                .WithMany()
                .HasForeignKey("CategoryId")
                .HasConstraintName("fk_expenses_categories_category_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            _ = b.HasOne("Domain.PaymentMethods.PaymentMethod", null)
                .WithMany()
                .HasForeignKey("PaymentMethodId")
                .HasConstraintName("fk_expenses_payment_methods_payment_method_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            _ = b.HasOne("Domain.Users.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .HasConstraintName("fk_expenses_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        _ = modelBuilder.Entity("Domain.Expenses.ExpenseTag", b =>
        {
            _ = b.HasOne("Domain.Expenses.Expense", null)
                .WithMany("Tags")
                .HasForeignKey("ExpenseId")
                .HasConstraintName("fk_expense_tag_expenses_expense_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            _ = b.HasOne("Domain.Tags.Tag", "Tag")
                .WithMany()
                .HasForeignKey("TagId")
                .HasConstraintName("fk_expense_tag_tags_tag_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        _ = modelBuilder.Entity("Domain.Roles.RolePermission", b =>
        {
            _ = b.HasOne("Domain.Roles.Role", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .HasConstraintName("fk_role_permissions_roles_role_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        _ = modelBuilder.Entity("Domain.Roles.UserRole", b =>
        {
            _ = b.HasOne("Domain.Roles.Role", null)
                .WithMany()
                .HasForeignKey("RoleId")
                .HasConstraintName("fk_user_roles_roles_role_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            _ = b.HasOne("Domain.Users.User", null)
                .WithMany()
                .HasForeignKey("UserId")
                .HasConstraintName("fk_user_roles_users_user_id")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();
        });

        _ = modelBuilder.Entity("Domain.Expenses.Expense", b =>
        {
            _ = b.Navigation("Tags");
        });
    }
}
